[tool.poetry]
name = "latimes"
version = "0.0.0"
description = "Convierte tiempos"
authors = ["Antonio Feregrino <antonio.feregrino@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
latimes = 'latimes.__main__:main'

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
pytz = "^2021.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
